/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "GP_Timers.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "LUNA_LIDAR.h"
extern uint16_t LUNA_dis;
extern uint16_t LUNA_AMP;
extern uint16_t LUNA_TEMP;
extern uint8_t LUNA_CheckSum;
int main(void)
{

	LUNA_INIT(CONTIOUS_RANGING_MODE,BYTE_9_CM);
    /* Loop forever */
	for(;;){
		MCAL_USART_SendData(LUNA_UART_INSTANT, (uint8_t)LUNA_dis);
		MCAL_USART_SendData(LUNA_UART_INSTANT, (LUNA_dis>>8));

		MCAL_USART_SendData(LUNA_UART_INSTANT, (uint8_t)LUNA_AMP);
		MCAL_USART_SendData(LUNA_UART_INSTANT, (LUNA_AMP>>8));

		MCAL_USART_SendData(LUNA_UART_INSTANT, (uint8_t)LUNA_TEMP);
		MCAL_USART_SendData(LUNA_UART_INSTANT, (LUNA_TEMP>>8));


		MCAL_USART_SendData(LUNA_UART_INSTANT, LUNA_CheckSum);

		_delay_s(TIM2, 1);
	}
}
