/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Platform_Types.h"
/*RCC REG*/
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *((volatile usint32_t  *)(RCC_BASE+ 0x18))
/*GPIO REG*/
#define GPIOA_BASE 0x40010800
#define GPIOA_CRH *((volatile usint32_t    *)(GPIOA_BASE+ 0x04))
#define GPIOA_CRL *((volatile usint32_t    *)(GPIOA_BASE+ 0x00))
#define GPIOA_ODR *((volatile usint32_t     *)(GPIOA_BASE+ 0x0C))
/*EXTI REG*/
#define EXTI_BAASE 0x40010400
#define EXTI_IMR *((volatile usint32_t    *)(EXTI_BAASE+ 0x00))
#define EXTI_RTSR *((volatile usint32_t    *)(EXTI_BAASE+ 0x08))
#define EXTI_PR *((volatile usint32_t    *)(EXTI_BAASE+ 0x14))
#define NVIC *((volatile usint32_t    *)(0xE000E100))
#define EXTI_FTSR *((volatile usint32_t    *)(EXTI_BAASE+ 0x0C))





/*AFIO REG*/
#define AFIO_BASE 0x40010000
#define AFIO_EXTICR1 *((volatile usint32_t    *)(AFIO_BASE+ 0x08))



void clock_init(){
	RCC_APB2ENR|=(1<<2);
	/*Bit 0 AFIOEN: Alternate function IO clock enable
	Set and cleared by software.
	0: Alternate Function IO clock disabled
	1: Alternate Function IO clock enabled*/
	RCC_APB2ENR|=(1<<0);

}
void GPIO_init(){
	GPIOA_CRH&=0xFF0FFFFF;
	GPIOA_CRH|=0x00200000;
	/*In input mode (MODE[1:0]=00):
	00: Analog mode
	01: Floating input (reset state)
	10: Input with pull-up / pull-down
	11: Reserved*/
	GPIOA_CRL&=0xFFFFFFF0;
	GPIOA_CRL|=0b0100;


}
void EXTI_init(){
	/* Bits 19:0 MRx: Interrupt Mask on line x
	0: Interrupt request from Line x is masked
	1: Interrupt request from Line x is not masked
	Note: Bit 19 is used in connectivity line devices only and is reserved otherwise.*/
	EXTI_IMR|=(1<<0);
	/*Bits 19:0 TRx: Rising trigger event configuration bit of line x
	0: Rising trigger disabled (for Event and Interrupt) for input line
	1: Rising trigger enabled (for Event and Interrupt) for input line.
	Note: Bit 19 is used in connectivity line devices only and is reserved otherwise.*/
	EXTI_RTSR|=(1<<0);
	EXTI_FTSR=0;
}

int main(void)
{
	/*Bits 15:0 EXTIx[3:0]: EXTI x configuration (x= 0 to 3)
	These bits are written by software to select the source input for EXTIx external interrupt.
	Refer to Section 10.2.5: External interrupt/event line mapping
	0000: PA[x] pin*/
	AFIO_EXTICR1 &=0xFFF0;
	EXTI_init();
	GPIO_init();
	clock_init();
	NVIC|=(1<<6);

	for(;;){
		// another sol.
		//		pins->pin.pin13 =	1; // led off


		//		pins->pin.pin13 =	0; // led on

		//		for(int i=0;i<5000;i++);


	}
}
void EXTI0_IRQHandler(void){
	GPIOA_ODR^=(1<<13);
	/*Bits 19:0 PRx: Pending bit
	0: No trigger request occurred
	1: selected trigger request occurred
	This bit is set when the selected edge event arrives on the external interrupt line. This bit is
	cleared by writing a ‘1’ into the bit.
	Note: Bit 19 is used in connectivity line devices only and is reserved otherwise.
	 */
	EXTI_PR|=(1<<0);
//	for(int i=0;i<5000;i++);

}
