/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "EEPROM.h"

uint8_t data[5]={0xF0,0xF1,0xF2,0xF3,0xF4};
uint8_t data1[5]={1,2,3,4,5};

uint8_t read_data[5];

int main(void)
{
	I2C_config_t I2C_CONFIG ={ENABLE,(SLAVE_ADD){0x02,DISABLE,0},Sm,F_100Khz,DISABLE,NULL};
	I2C_init(I2C1,&I2C_CONFIG);
	EPPROM_write(I2C1,data,5,0x01);
	EPPROM_READ(I2C1,read_data,5,0x01);
    /* Loop forever */
	EPPROM_write(I2C1,data1,5,0xFFAA);
	EPPROM_READ(I2C1,read_data,5,0xFFAA);
	for(;;){





	}
}
