/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Platform_Types.h"
/*RCC REG*/
#define RCC_BASE 0x40021000
#define RCC_APB2ENR *((volatile usint32_t  *)(RCC_BASE+ 0x18))
/*GPIO REG*/
#define GPIOA_BASE 0x40010800
#define GPIOB_BASE 0x40010C00
#define GPIOA_CRH *((volatile usint32_t    *)(GPIOA_BASE+ 0x04))
#define GPIOA_CRL *((volatile usint32_t    *)(GPIOA_BASE+ 0x00))
#define GPIOA_ODR *((volatile usint32_t     *)(GPIOA_BASE+ 0x0C))
#define GPIOA_IDR *((volatile usint32_t     *)(GPIOA_BASE+ 0x08))

/*-----*/
#define GPIOB_CRH *((volatile usint32_t    *)(GPIOB_BASE+ 0x04))
#define GPIOB_CRL *((volatile usint32_t    *)(GPIOB_BASE+ 0x00))
#define GPIOB_ODR *((volatile usint32_t     *)(GPIOB_BASE+ 0x0C))
#define GPIOB_IDR *((volatile usint32_t     *)(GPIOB_BASE+ 0x08))
/*EXTI REG*/
#define EXTI_BAASE 0x40010400
#define EXTI_IMR *((volatile usint32_t    *)(EXTI_BAASE+ 0x00))
#define EXTI_RTSR *((volatile usint32_t    *)(EXTI_BAASE+ 0x08))
#define EXTI_PR *((volatile usint32_t    *)(EXTI_BAASE+ 0x14))
#define NVIC *((volatile usint32_t    *)(0xE000E100))
#define EXTI_FTSR *((volatile usint32_t    *)(EXTI_BAASE+ 0x0C))





/*AFIO REG*/
#define AFIO_BASE 0x40010000
#define AFIO_EXTICR1 *((volatile usint32_t    *)(AFIO_BASE+ 0x08))


#define BIT_IS_SET(REG,num) (REG &(1<<num))


void clock_init(){
	RCC_APB2ENR|=(1<<2);
	/*Bit 0 AFIOEN: Alternate function IO clock enable
	Set and cleared by software.
	0: Alternate Function IO clock disabled
	1: Alternate Function IO clock enabled*/
	RCC_APB2ENR|=(1<<0);
	RCC_APB2ENR|=(1<<3);

}
void GPIO_init(){
	GPIOA_CRL &=0xFFFFFF00;
	GPIOA_CRL |=(0b01000100);
	/*PORTB PIN 1 AS OUTPUT PUSH PULL*/
	GPIOB_CRL&=0xFFFFFF0F; // PORT A PIN 1 AS FLOATING INPUT
	GPIOB_CRL|=0x20;
	/*PORTB PIN 13 AS OUTPUT PUSH PULL*/
	GPIOB_CRH&=0xFF0FFFFF; // PORT A PIN 13 AS OUTPUT
	GPIOB_CRH|=0x00200000;
}
void EXTI_init(){
	/* Bits 19:0 MRx: Interrupt Mask on line x
	0: Interrupt request from Line x is masked
	1: Interrupt request from Line x is not masked
	Note: Bit 19 is used in connectivity line devices only and is reserved otherwise.*/
	EXTI_IMR|=(0b11<<0);
	/*Bits 19:0 TRx: Rising trigger event configuration bit of line x
	0: Rising trigger disabled (for Event and Interrupt) for input line
	1: Rising trigger enabled (for Event and Interrupt) for input line.
	Note: Bit 19 is used in connectivity line devices only and is reserved otherwise.*/
	EXTI_RTSR|=(1<<0);
	EXTI_RTSR|=(1<<1);

	EXTI_FTSR|=(1<<1);
}

int main(void)
{
	NVIC|=(1<<6)|(1<<7);

	EXTI_init();
	clock_init();
	GPIO_init();
	AFIO_EXTICR1 &=0xFF00;
	for(;;){

		GPIOB_ODR |=(1<<1) |(1<<13);
		for(int i=0;i<255;i++)
			for(int j=0;j<255;j++);


	}
}
void EXTI0_IRQHandler(void){
	GPIOB_ODR ^=(1<<1);
	/*Bits 19:0 PRx: Pending bit
	0: No trigger request occurred
	1: selected trigger request occurred
	This bit is set when the selected edge event arrives on the external interrupt line. This bit is
	cleared by writing a ‘1’ into the bit.
	Note: Bit 19 is used in connectivity line devices only and is reserved otherwise.
	 */
	for(int i=0;i<255;i++)
		for(int j=0;j<255;j++);
	EXTI_PR|=(1<<0);
//	for(int i=0;i<5000;i++);

}
void EXTI1_IRQHandler (void){

		GPIOB_ODR ^=(1<<13);

		for(int i=0;i<255;i++)
			for(int j=0;j<255;j++);
	EXTI_PR|=(1<<1);

}
