/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include "scheduler.h"
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

uint8_t TASKA_LED=0;
uint8_t TASKB_LED=0;
uint8_t TASKC_LED=0;
uint8_t TASKD_LED=0;
uint8_t TASKE_LED=0;

void TASKA_Handler();
void TASKB_Handler();
void TASKC_Handler();
void TASKD_Handler();
void TASKE_Handler();

Task_sitting_t TASKA={"TASKA",10,1024,TASKA_Handler};
Task_sitting_t TASKB={"TASKB",10,1024,TASKB_Handler};
Task_sitting_t TASKC={"TASKC",10,1024,TASKC_Handler};
Task_sitting_t TASKD={"TASKD",10,1024,TASKD_Handler};
Task_sitting_t TASKE={"TASKE",1,1024,TASKE_Handler};
Mutex_sitting MUTEX1={"USART"};
void TASKA_Handler(){
	 uint32_t counter=0;

	while(1){
		TASKA_LED^=1;
		if (counter++ ==0xFF){
		Acquire_Mutex(&MUTEX1,&TASKA);
		}
	}
}
void TASKB_Handler(){

	while(1){
		TASKB_LED^=1;

	}
}
void TASKC_Handler(){
	while(1)		TASKC_LED^=1;

}
void TASKD_Handler(){
	while(1)		TASKD_LED^=1;

}
void TASKE_Handler(){
	 uint32_t counter=0;
	while(1)	{
		TASKE_LED^=1;
		if(counter++ ==0xFF){
			OS_TASK_wait(&TASKE, 100);
		}else if(counter == 0xfFf){
			Acquire_Mutex(&MUTEX1,&TASKE);

		}

	}




}
int main(void)
{
	HW_init();
	if(RTOS_init()!=NO_Error)
		while(1);
	RTOS_Create_Task(&TASKA);
	RTOS_Create_Task(&TASKB);
	RTOS_Create_Task(&TASKC);
	RTOS_Create_Task(&TASKD);
	RTOS_Create_Task(&TASKE);


	OS_Active_TASK(&TASKA);
	OS_Active_TASK(&TASKB);
	OS_Active_TASK(&TASKC);
	OS_Active_TASK(&TASKD);
	OS_Active_TASK(&TASKE);


	OS_start();

	//	Main_OS();

	/* Loop forever */
	for(;;);
}
