/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */
#include "USART_Driver.h"
#include "GP_Timers.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
uint8_t GR_TSR_FLAG_rec=0;
uint16_t GR_TSR_FLAG_OLED=0;
uint8_t GR_TSR_FLAG_OLED_send=0;
uint8_t temp=0;
uint8_t temp2=0;

uint8_t i=0;
uint8_t y=0;

uint8_t GR_TSR_FLAG_START=0xFF;

void call_Back(void){
	if(	USART1->SR &(1<<5)){
		GR_TSR_FLAG_rec=	MCAL_USART_ReciveData(USART1);


	}
	/*
	0x38 0x2A
	0x0038
	0x0008

	0x0000 | 0x0008
	0x0008
*/

	if(GR_TSR_FLAG_rec != '*'){
		GR_TSR_FLAG_OLED = (GR_TSR_FLAG_OLED<<8)| GR_TSR_FLAG_rec;
	}else{
		GR_TSR_FLAG_OLED &=0x0F0F;
		GR_TSR_FLAG_OLED_send = ((GR_TSR_FLAG_OLED &0x0F00)>>4) |((GR_TSR_FLAG_OLED&0x000F));
		GR_TSR_FLAG_OLED=0;

	}





}
void TSR_START(void){
	MCAL_USART_SendData(USART1, GR_TSR_FLAG_START);

}
int main(void)
{
	USART_Config_t UART1_CON={115200,EGHIT_BITS,Parity_DISABLE,Interrupt,ONE_STOP_BIT,Disabled,Asynchronous,call_Back};
	MCAL_USART_init(USART1, &UART1_CON);
	PIN_config PINx={PIN_0,OUTPUT_PP,SPEED_10};
	MCAL_GPIO_init(GPIOA, &PINx);

	/* Loop forever */
	GR_TSR_FLAG_START=0x01;

	for(;;){
		TSR_START();

		if(GR_TSR_FLAG_OLED_send!=0x99){
		MCAL_write_PIN(GPIOA, PIN_0, 1);

		}else{
			MCAL_write_PIN(GPIOA, PIN_0, 0);

		}



		MCAL_USART_SendData(USART1, GR_TSR_FLAG_OLED_send);
			_delay_s(TIM2, 1);





	}
}
