/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "SPI_EEPROM.h"
#include  "Timer.h"
#include "EXTI_Driver.h"
#include "USART_Driver.h"
#include "main.h"
/********************DEFINES**********************/
#define ADMIN_PASSWORD_EEPROM_ADDRESS		0xF3
#define ADMIN_PASSWORD_LEN					8
#define	USERS								3

/*********************GLOBAL CONFIGRATION********************/


USART_Config_t UART_CONFIG_V={115200,EGHIT_BITS,Parity_DISABLE,Interrupt,ONE_STOP_BIT,Disabled,Asynchronous};
EXTI_config_t	EXTI_PIR1={(GPIO_CONFIG_t){8,GPIOA,PIN_8,23},FALLING,ENABLE};
EXTI_config_t	EXTI_PIR2={(GPIO_CONFIG_t){1,GPIOA,PIN_1,7},FALLING,ENABLE};
/*******************************************/

void (*g_f_MASTER_state)(void) =ADMIN_OLD_PASSWORD_CHECK;
void (*g_f_USER_state)(void)=NULL;
int main(void)
{
	int data[4]={1,2,3,4};
	ALL_PREPHRAL_Init();
	SPI_EEPROM_WRITE(SPI1, 0x0001, data,4);
	SPI_EEPROM_READ(SPI1, 0x0001, &data, 4);

	for(;;){

//		g_f_MASTER_state();
}
}


/*======================================================================================================
 * FUNC NAME ----> ALL_PREPHRAL_Init
 * BRIEF     ----> USE TO INIT ALL PREPHRALS
 * PARAM1[IN]----> VOID
 * RETAVAL	 ---->
 * NOTE		 ---->
 *
 */
void ALL_PREPHRAL_Init(void){
	Timer2_init();
	SPI_EEPROM_init(SPI1);
	MCAL_USART_init(USART1,&UART_CONFIG_V);
	MCAL_USART_init(USART2,&UART_CONFIG_V);
	KEYPAD_init();
	LCD_init();
	MCAL_EXTI_init(&EXTI_PIR1);
	MCAL_EXTI_init(&EXTI_PIR2);
	LCD_init_V2();

}
/*======================================================================================================
 * FUNC NAME ----> ADMIN_OLD_PASSWORD_CHECK
 * BRIEF     ----> USE TO CHECK THERE IS PASSWORD FOR ADMIN OR NOT
 * PARAM1[IN]----> VOID
 * RETAVAL	 ---->
 * NOTE		 ---->
 *
 */
void ADMIN_OLD_PASSWORD_CHECK(){
	uint8_t PASSWORD[ADMIN_PASSWORD_LEN]={0};

	SPI_EEPROM_READ(SPI1, ADMIN_PASSWORD_EEPROM_ADDRESS, &PASSWORD, ADMIN_PASSWORD_LEN);

		for(int i=0;i<ADMIN_PASSWORD_LEN;i++)
		{
			if(PASSWORD[i]!=0xFF){
				g_f_MASTER_state=ADMIN_ENTER_PASSWORD;
				break;
			}else{
				g_f_MASTER_state=ADMIN_CREATE_PASSWORD;

			}
		}
}

/*======================================================================================================
 * FUNC NAME ----> ADMIN_ENTER_PASSWORD
 * BRIEF     ----> USE TO CHECK THE ENTERD PASSWORD IS CORRECT OR NOT
 * PARAM1[IN]----> VOID
 * RETAVAL	 ---->
 * NOTE		 ---->
 *
 */
void ADMIN_ENTER_PASSWORD(){
	uint8_t PASSWORD[ADMIN_PASSWORD_LEN],pass;
	LCD_clearScreen();
	LCD_sendString("Hello Admin,");
	LCD_moveCURSER(1,0);
	LCD_sendString("Please Enter The PASSWORD:");
	for(int i=0;i<ADMIN_PASSWORD_LEN;){
		pass=Get_Pressed_KEY();
		switch(pass){
		case 'N':
			break;
		default:
			i++;
			PASSWORD[i]=pass;
			LCD_sendCharcter('*');

		}
	}
	if(ADMIN_PASSWORD_CHECK(&PASSWORD)){
		g_f_MASTER_state=ADMIN_mian_menu;
	}else{
		g_f_MASTER_state=ADMIN_ENTER_PASSWORD;
	}

}
/*======================================================================================================
 * FUNC NAME ----> ADMIN_CREATE_PASSWORD
 * BRIEF     ----> USE TO ENTER A NEW PASSWORD AND SAVE IT IN EEPROM
 * PARAM1[IN]----> VOID
 * RETAVAL	 ---->
 * NOTE		 ---->
 *
 */
void ADMIN_CREATE_PASSWORD(){
	uint8_t PASSWORD[ADMIN_PASSWORD_LEN]={0},pass=0;
	LCD_clearScreen();
	LCD_sendString("Hello Admin,");
	LCD_moveCURSER(1,0);
	LCD_sendString("Please CREATE");
	LCD_moveCURSER(2,0);
	LCD_sendString("The PASSWORD:");

	for(int i=0;i<ADMIN_PASSWORD_LEN;){
		pass=Get_Pressed_KEY();
		switch(pass){
		case 'N':
			break;
		default:
			i++;
			PASSWORD[i]=pass;
			LCD_sendCharcter('*');


		}
	}
	SPI_EEPROM_WRITE(SPI1, 0x00, &PASSWORD, ADMIN_PASSWORD_LEN);
	g_f_MASTER_state=ADMIN_ENTER_PASSWORD;
}
/*======================================================================================================
 * FUNC NAME ----> ADMIN_PASSWORD_CHECK
 * BRIEF     ----> USE TO CHECK THE ENTERD PASSWORD IS CORRECT OR NOT
 * PARAM1[IN]----> THE COMPARE PASSOWRD
 * RETAVAL	 ---->
 * NOTE		 ---->
 *
 */
uint8_t ADMIN_PASSWORD_CHECK(int *data){
	uint8_t PASSWORD[ADMIN_PASSWORD_LEN]={0};
	SPI_EEPROM_READ(SPI1, ADMIN_PASSWORD_EEPROM_ADDRESS, &PASSWORD, ADMIN_PASSWORD_LEN);
	for(int i=0;i<ADMIN_PASSWORD_LEN;i++){
		if(*data!=PASSWORD[i]){
			return 0;
		}else{
			data++;
		}
	}
	return 1;
}

void ADMIN_mian_menu(){
LCD_clearScreen();
LCD_sendString("MAIN MENU");
}

